---
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  GuacamoleInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-123456'
      InstanceType: 't2.micro'
      KeyName: 'my-key-pair'
      SecurityGroupIds:
        - 'sg-123456'
      SubnetId: 'subnet-123456'

  GuacamoleSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Allow HTTP and SSH access'
      VpcId: 'vpc-123456'
      SecurityGroupIngress:
        - IpProtocol: 'tcp'
          FromPort: '80'
          ToPort: '80'
          CidrIp: '0.0.0.0/0'
        - IpProtocol: 'tcp'
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'
